# Generated by Django 5.0.6 on 2024-10-30 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('comment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.carmodel')),
            ],
        ),
    ]
