# Generated by Django 5.0.6 on 2024-10-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_remove_carowner_owned_car_carowner_owned_car'),
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='owned_car',
        ),
        migrations.AlterField(
            model_name='carowner',
            name='owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='carowner',
            name='owned_car',
            field=models.ManyToManyField(to='car_app.carmodel'),
        ),
    ]
