# Generated by Django 5.0.6 on 2024-10-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_carowner_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='owned_car',
        ),
        migrations.AddField(
            model_name='carowner',
            name='owned_car',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
